openapi: 3.0.3
info:
  title: Nickname extraction service API
  description: Service for extracting usernames from email addresses
  version: 1.0.0
  contact:
    name: Maxim Berezhnoy
    url: https://github.com
paths:
  /emails/nickname:
    post:
      tags:
        - Nicknames
      summary: Extract a nickname from an email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextRequest'
      responses:
        200:
          description: Nickname has been successfully extracted
          content:
            application/json:
              schema:
                $ref: "#components/schemas/NicknameResponse"
        404:
          description: Page not found
        422:
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ApiErrorResponse"

    get:
      tags:
        - Nicknames
      summary: Get nickname request history
      responses:
        200:
          description: Nickname has been successfully extracted
          content:
            application/json:
              schema:
                $ref: "#components/schemas/NicknamesHistoryResponse"
        400:
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ApiErrorResponse"
        500:
          description: The server is unavailable

  /emails/domain:
    post:
      tags:
        - Domains
      summary: Extract a domain from an email address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextRequest'
      responses:
        200:
          description: Domain has been successfully extracted
          content:
            application/json:
              schema:
                $ref: "#components/schemas/DomainResponse"
        404:
          description: Page not found
        422:
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ApiErrorResponse"

    get:
      tags:
        - Domains
      summary: Get domain request history
      responses:
        200:
          description: The request history was successfully received
          content:
            application/json:
              schema:
                $ref: "#components/schemas/DomainsHistoryResponse"
        400:
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ApiErrorResponse"
        500:
          description: The server is unavailable

components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        description:
          type: string
        code:
          type: string
        exceptionMessage:
          type: string

    TextRequest:
      type: object
      properties:
        text:
          type: string

    NicknameResponse:
      type: object
      properties:
        nickname:
          type: string

    DomainResponse:
      type: object
      properties:
        domain:
          type: string

    NicknamesHistoryResponse:
      type: object
      properties:
        nicknames:
          type: array
          items:
            type: string
        total:
          type: integer
          format: int64

    DomainsHistoryResponse:
      type: object
      properties:
        domains:
          type: array
          items:
            type: string
        total:
          type: integer
          format: int64